#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiRepuestos.View
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PlanillaDePagoMensual")]
	public partial class conexionlinqIHSSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertIHSS(IHSS instance);
    partial void UpdateIHSS(IHSS instance);
    partial void DeleteIHSS(IHSS instance);
    #endregion
		
		public conexionlinqIHSSDataContext() : 
				base(global::MultiRepuestos.Properties.Settings.Default.PlanillaDePagoMensualConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqIHSSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqIHSSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqIHSSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqIHSSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IHSS> IHSS
		{
			get
			{
				return this.GetTable<IHSS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Planilla.IHSS")]
	public partial class IHSS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private decimal _GastosMedicos;
		
		private decimal _SalarioTecho;
		
		private System.Nullable<System.DateTime> _Fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnGastosMedicosChanging(decimal value);
    partial void OnGastosMedicosChanged();
    partial void OnSalarioTechoChanging(decimal value);
    partial void OnSalarioTechoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public IHSS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GastosMedicos", DbType="Decimal(10,2) NOT NULL")]
		public decimal GastosMedicos
		{
			get
			{
				return this._GastosMedicos;
			}
			set
			{
				if ((this._GastosMedicos != value))
				{
					this.OnGastosMedicosChanging(value);
					this.SendPropertyChanging();
					this._GastosMedicos = value;
					this.SendPropertyChanged("GastosMedicos");
					this.OnGastosMedicosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalarioTecho", DbType="Decimal(10,2) NOT NULL")]
		public decimal SalarioTecho
		{
			get
			{
				return this._SalarioTecho;
			}
			set
			{
				if ((this._SalarioTecho != value))
				{
					this.OnSalarioTechoChanging(value);
					this.SendPropertyChanging();
					this._SalarioTecho = value;
					this.SendPropertyChanged("SalarioTecho");
					this.OnSalarioTechoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
