<?xml version="1.0" encoding="utf-8"?><Database Name="PlanillaDePagoMensual" Class="conexionlinqIHSSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-M6GR8FE\SQLEXPRESS02;Initial Catalog=PlanillaDePagoMensual;Integrated Security=True" SettingsObjectName="MultiRepuestos.Properties.Settings" SettingsPropertyName="PlanillaDePagoMensualConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Planilla.IHSS" Member="IHSS">
    <Type Name="IHSS">
      <Column Name="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GastosMedicos" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="SalarioTecho" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>